# 端口配置
server:
  port: 6001

# 服务名配置
spring:
  application:
    name: locomotive-eureka

  # 权限配置
  security:
    user:
      name: zez
      password: zez

# 服务注册中心配置
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  server:
    #测试环境禁用自我保护模式
    enable-self-preservation: false

  # 客户端连接配置
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultone: http://{eureka.instance.hostname}:${server.port}/eureka/
